# Simple workflow for building and deploying markdown files using staticgen
name: "Build and deploy markdown using staticgen"
description: Builds static files and deploys using pages deploy
author: Jashon Osala
inputs:
  url:
    description: "Base url for the repos github-pages"
    required: true
    default: ""
  build:
    description: "Path of directory to output build"
    required: false
    default: "build"
  md:
    description: "Path of directory containing markdown files"
    required: true
    default: "markdown"
  
  # Generate build files 
runs:
    using: composite
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install staticgen
        shell: bash
        run: |
          git clone -n https://github.com/osala-eng/developer-challange.git /tmp/staticgen --depth 1
          cd /tmp/staticgen
          git checkout HEAD static-site-generator
          cd static-site-generator
          sudo ./install
          cd ~
          rm -rf /tmp/staticgen
      - name: Checkout
        uses: actions/checkout@v3
      - name: Generate build
        run: sudo staticgen --deploy-to-github "${MD_PATH}" "$BUILD_PATH" "${INPUT_URL}"
        env:
          INPUT_URL: ${{ inputs.url }}
          MD_PATH: ${{ inputs.md }}
          BUILD_PATH: ${{ inputs.build }}
      
      # Upload build artifacs
      - name: Upload build using upload page artifacts
        uses: actions/upload-pages-artifact@v1
        with:
          path: ${{ inputs.build }}
          name: staticgen

      # Deploy to github
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
        with:
          artifact_name: staticgen
